// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1MI6L4rpGkwZa_zIK3xkuiRd7hXV1DI',
    appId: '1:179067274484:web:b2abd3609de05381524aa1',
    messagingSenderId: '179067274484',
    projectId: 'starwarexamen',
    authDomain: 'starwarexamen.firebaseapp.com',
    storageBucket: 'starwarexamen.firebasestorage.app',
    measurementId: 'G-XFV4QYN20D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHntcRvWMm4xrqhd3nShIlQ1qPfKxhbfY',
    appId: '1:179067274484:android:f0dbdc4ee560b138524aa1',
    messagingSenderId: '179067274484',
    projectId: 'starwarexamen',
    storageBucket: 'starwarexamen.firebasestorage.app',
  );
}
